version: 0.2

phases:
  build:
    commands:
    - make build-cross-platform e2e-tests-binary e2e-test ginkgo
    - aws s3 cp _bin/amd64/nodeadm s3://$ARTIFACTS_BUCKET/latest-pre/linux/amd64/nodeadm
    - aws s3 cp _bin/arm64/nodeadm s3://$ARTIFACTS_BUCKET/latest-pre/linux/arm64/nodeadm
    - aws s3 cp _bin/e2e-test s3://$ARTIFACTS_BUCKET/latest-pre/e2e-test
    - aws s3 cp _bin/e2e.test s3://$ARTIFACTS_BUCKET/latest-pre/e2e.test

cache:
  paths:
    - '/root/.cache/go-build/**/*'
    - '/go/pkg/mod/**/*'

artifacts:
  files:
  - "_bin/**/*"
  - "buildspecs/*"
  - "hack/*"
  - "test/e2e/cni/testdata/**/*"  
